backend:
  locale: 'de'
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'
  # name: test-repo

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: 'neuigkeiten'
    label: 'Neuigkeiten'
    folder: 'content/neuigkeiten'
    create: true
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'neuigkeiten',
        }
      - {
          label: 'Der Titel des Artikels',
          name: 'title',
          widget: 'string',
          required: true,
        }
      - {
          label: 'Slug',
          name: 'slug',
          widget: 'string',
          hint: 'Der Slug fuer diesen Artikel. (z.B.: 2020-12-16-jahresprogramm-2020)',
          pattern:
            [
              '^[A-Za-z0-9][A-Za-z0-9-]*$',
              'Dieser Slug hat nicht das richtige Format. Er darf nur aus Zahlen (0-9), Buchstaben (A-Z) und dem Gedankenstrich (-) bestehen.',
            ],
          required: true,
        }
      - {
          label: 'Kurze Beschreibung',
          name: 'description',
          widget: 'text',
          hint: 'Diese kurze Beschreibung wird hinterher auf der Startseite beim Anzeigen der Neuigkeit gezeigt sowohl als auch fuer SEO Zwecke benutzt. (max. 170 Zeichen)',
          required: true,
        }
      - { label: 'Text', name: 'body', widget: 'markdown', required: true }
  - name: 'pages'
    label: 'Veranstaltungen und mehr'
    files:
      - file: 'content/page/veranstaltungen.md'
        label: 'Liste der Veranstaltungen'
        name: 'veranstaltungen'
        fields:
          - label: 'Veranstaltungen'
            name: 'veranstaltungen-liste'
            widget: 'list'
            collapsed: true
            summary: '{{fields.title}}'
            fields:
              - {
                  label: 'Zeige im Karousel auf der Startseite',
                  name: 'featured',
                  widget: 'boolean',
                  default: true,
                  hint: 'Wenn dieser Schalter aktiv ist, wird diese Veranstaltung im Karousel auf der Startseite angezeigt.',
                }
              - {
                  label: 'Der Titel der Veranstaltung',
                  name: 'title',
                  widget: 'string',
                  default: 'Leiten und Beraten von Gruppen und Teams',
                  required: true,
                }
              - {
                  label: 'Link zur Veranstaltungsseite auf igo',
                  name: 'link',
                  widget: 'string',
                  hint: 'Der Link fuer diese Veranstaltung. (z.B.: https://www.igo-muenster.de/haette-ich-das-gewusst/)',
                  required: true,
                }
              - {
                  label: 'Kurze Beschreibung',
                  name: 'description',
                  default: 'Wenn Sie mit Gruppen oder Teams oder in einer Leitungsfunktion arbeiten, ganz gleich im Unternehmen, in der Schule oder in der Verwaltung, haben Sie in vielerlei Bezügen mit deren Dynamik zu tun.',
                  widget: 'text',
                  hint: 'Diese kurze Beschreibung dient wird beim Anzeigen der Veranstaltungen genutzt. (max. 170 Zeichen)',
                  required: true,
                }
              - {
                  label: 'Prospekt Foto',
                  name: 'thumbnail',
                  widget: 'image',
                  hint: 'Lade hier das Prospektfoto der Veranstaltung hoch.',
                  required: true,
                }
