backend:
  name: test-repo
  locale: 'de'

  # name: git-gateway
  # branch: master
  # commit_messages:
  #   create: 'Create {{collection}} “{{slug}}”'
  #   update: 'Update {{collection}} “{{slug}}”'
  #   delete: 'Delete {{collection}} “{{slug}}”'
  #   uploadMedia: '[skip ci] Upload “{{path}}”'
  #   deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: 'neuigkeiten'
    label: 'Neuigkeiten'
    folder: 'content/neuigkeiten'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'neuigkeiten',
        }
      - {
          label: 'Der Titel des Artikels',
          name: 'title',
          widget: 'string',
          required: true,
        }
      - {
          label: 'Slug',
          name: 'slug',
          widget: 'string',
          hint: 'Der Slug fuer diesen Artikel. (z.B.: 2020-12-16-jahresprogramm-2020)',
          pattern:
            [
              '^[A-Za-z0-9][A-Za-z0-9-]*$',
              'Dieser Slug hat nicht das richtige Format. Er darf nur aus Zahlen (0-9), Buchstaben (A-Z) und dem Gedankenstrich (-) bestehen.',
            ],
          required: true,
        }
      - {
          label: 'Kurze Beschreibung',
          name: 'description',
          widget: 'text',
          hint: 'Diese kurze Beschreibung wird hinterher auf der Startseite beim Anzeigen der Neuigkeit gezeigt sowohl als auch fuer SEO Zwecke benutzt. (max. 150 Zeichen)',
          required: true,
        }
      - { label: 'Text', name: 'body', widget: 'markdown', required: true }
